version: '3.1'

services:

  db:
    image: aeros-pg:latest
    restart: unless-stopped
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USERNAME: maelstrom
      POSTGRES_PASSWORD: aeflheim
      POSTGRES_DB: quasardb
    volumes:
      - /mnt/data:/var/lib/postgresql/data
