spring:
  application:
    name: bifrost
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${JDBC_URL}
